### ISSUE TITLE
Error on : {"AADSTS65001: No permission to access user information is configured for '...' application, or it is expired or revoked.

### ISSUE THREAD

**Issue by rquintino** [Vtek/PowerBI.Api.Client#1]
Hi Sylvain , thanks for the package, very cool.

We were trying to change some PowerBI API samples to use the package, but getting this error:
Error on : {"AADSTS65001: No permission to access user information is configured for '...' application, or it is expired or revoked.
 at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, String clientId, UserCredential userCredential)
   at PowerBI.Api.Client.PowerBIClient.Authenticate() in c:\Users\joana.barbosa\Downloads\PowerBI.Api.Client-master\PowerBI.Api.Client-master\src\PowerBI.Api.Client\PowerBIClient.cs: line 110

We can get the token using the standard oauth login/authorize app popup (we are using powerbi getting started sample from Josh Kaplan, works fine)  but not using the user/password (silent usercredential ?). What am I missing?

In azure the app is created as Native client application with PowerBI Service delegated Permissions (all three permissions) and also Azure AD default permission: enable sso and read user profiles. 

-tried creating another azure app just in case, same error
-validated credentials are working ok, forcing an incorrect password return expected invalid login

Thanks!
Rui

![image](https://cloud.githubusercontent.com/assets/10835742/6186616/9ac2aaea-b373-11e4-95fe-6cb539c74a86.png)

![image](https://cloud.githubusercontent.com/assets/10835742/6186618/a3e1a612-b373-11e4-9c8e-ee273cfd4333.png)

**Comment by Vtek** [comment]
Hi Rui,

Thank to post the issue with all the details.
You're case seems to be not implement in the library. In our team we decide to create the library to use it on powerbi.com, so the UserCredential instance is always required...

For me It's a mistake, this feature must be avaible in the library (like in Josh sample). 

I'm thinking to change user & password configuration proprety required flag to false. In this case they will be optionals !

I do my best to add it in the library soon  ;)

Many thanks,
Sylvain

**Comment by rquintino** [comment]
Hi Sylvain, thanks for the feedback but maybe I didnt explain myself
properly :), we actually also want to use the username/pass and not the
oauth popup. So we have the proper user/pass on config but just doesnt work.

Running your package sample project, only setting the config values to our
appid /user/pass throws that error.

Rui

**Comment by Vtek** [comment]
Ok sorry ! :)

I read some informations about this error on the internet, and there are no answer (of course). I need to make a little test with the same configuration on Azure.

**Comment by Vtek** [comment]
Hi Rui,

This week-end i try to reproduce your problem. I want to re-build an azure configuration but i forgot that we can't made that with our corporation account (culture problem). I remember it was one of our team member who create the Azure AD and configure it. So i ask him for more information about the configuration we use to deal with OAuth authentication.

I can suggest you to check if the Authority you set corresponding to your configuration and if your native application ClientId is the right one.

Hope i get more information about our configuration soon.
I'm thinking about write a little page on the wiki about the OAuth configuration.

**Comment by Vtek** [comment]
Hi Rui,

Me again, i've got our app configuration : 

![azurepowerpiauthorize](https://cloud.githubusercontent.com/assets/3357643/6209623/12efcd26-b5c8-11e4-9370-998e9e8e19c1.PNG)

![azurepowerpiauthorize_2](https://cloud.githubusercontent.com/assets/3357643/6209630/1a1251f0-b5c8-11e4-8937-56b9b59b771d.PNG)

![azurepowerpiauthorize_3](https://cloud.githubusercontent.com/assets/3357643/6209631/1d7f287c-b5c8-11e4-9c42-a2553d732591.PNG)

I hope this screen can help you to solve your problem !

**Comment by Vtek** [comment]
Hi Rui,

I haven't new from you so i think you resolve this problem :)
