### ISSUE TITLE
While calling GetDatasets(), null reference exception throwing. For this GetId also not working.. need urgent help!

### ISSUE THREAD

**Issue by PriyankaDK** [Vtek/PowerBI.Api.Client#27]

**Comment by Vtek** [comment]
Hi, sorry for the long delay of this answer.

Well, it's hard to find a solution with just a NullReferenceException.
Is your credentials and configuration are ok ?

**Comment by Vtek** [comment]
Issue may be due to the DatasetCollection property name.
It's now fix, check the #33 issue for more information

**Comment by Vtek** [comment]
1.2 alpha version avaible on NuGet (Pre version).
Please read the 1.2 wiki page : https://github.com/Vtek/PowerBI.Api.Client/wiki/Version-1.2-alpha

A++
Sylvain
