### ISSUE TITLE
Support for Multi-tenant web application / application with configuration from a database.

### ISSUE THREAD

**Issue by morSchmidt** [Vtek/PowerBI.Api.Client#28]
We would like to use your library for both our online multitenant solution, however with a static constructor reading from a config file this wouldn't support having one application writing to different PowerBI users.

Additionally in our onsite application we have one database where we keep our configuration, saving powerBI configuration in the database is alot more convinient than maintaining local configuration files or having our application write these.

**Comment by Vtek** [comment]
Hi,
That's correct. The library was design to work with a single user.
Did you have suggestions to deal with multiple user ?
It will be hard to change this without a big update...

I am going to think about it !

**Comment by nate-fr** [comment]
I would also be interested by such feature.
Vtek, I could help a bit once you know where you are heading with this.

**Comment by Vtek** [comment]
Hi,

With the resolve of Issue #30 , the ConfigurationSection requirement is break.
This feature will be the next to be avaible. I decide to not break the library behavior and just add an overloading Do method with all the parameters need to deal with multiple users !

**Comment by Vtek** [comment]
1.2 alpha version avaible on NuGet (Pre version).
Please read the 1.2 wiki page : https://github.com/Vtek/PowerBI.Api.Client/wiki/Version-1.2-alpha

A++
Sylvain
