### ISSUE TITLE
Expose the configuration so that it doesn't have to be in config

### ISSUE THREAD

**Issue by mikeblakeuk** [Vtek/PowerBI.Api.Client#30]
I want to configure the Client in code, not config.
Thanks

**Comment by Vtek** [comment]
Hi, 

This will be available soon.

Best,
Sylvain

**Comment by Vtek** [comment]
Feature is avaible on v1.2 branch. You can use the classic library to test it : https://github.com/Vtek/PowerBI.Api.Client/tree/v1.2/dist/Classic

Just call the initialize method like this : 
PowerBIClient.Initialize("myUrl", "myAuthority", "myResource", "myClient", "myUser", "myPassword");

Nuget package will be avaible soon !

++

**Comment by mikeblakeuk** [comment]
Hi Vtek, any word on this? Thanks

**Comment by Vtek** [comment]
The configuration is expose on 1.2 branch. This will be in the PreRelease on Nuget at 15/08 with all remaining complete and available features on the 1.2 branch.

You can currently test the feature with the .dll in dist :).

I start multi-tenant too, but need more work to be ok !

**Comment by Vtek** [comment]
1.2 alpha version avaible on NuGet (Pre version).
Please read the 1.2 wiki page : https://github.com/Vtek/PowerBI.Api.Client/wiki/Version-1.2-alpha

A++
Sylvain
